# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

pool:
  vmImage: 'ubuntu-16.04' # other options: 'ubuntu-16.04', 'macOS-10.13', 'vs2017-win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  Major: 1
  Minor: 0
  Patch: 0

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.1.403' 

- script: dotnet restore
- script: dotnet build --configuration $(buildConfiguration) --no-restore --no-incremental
- script: dotnet test test/AutoUpgrade.Tests/AutoUpgrade.Tests.csproj --configuration $(buildConfiguration) --no-build --no-restore --list-tests
    
#- task: DotNetCoreCLI@2
#  inputs:
#    command: test
#    projects: '**/*Tests/*.csproj'
#    arguments: '--configuration $(buildConfiguration) --collect "Code coverage" --no-build --no-restore --list-tests'

- script: dotnet pack src/AutoUpgrade/AutoUpgrade.csproj -p:PackageVersion=$(Major).$(Minor).$(Patch) --no-build --no-restore --configuration $(buildConfiguration) --output $(Build.BinariesDirectory)

# - script: dotnet nuget push $(Build.BinariesDirectory)/autoupgrade.$(Major).$(Minor).$(Patch).nupkg --source https://nuget.org/api/v2/ --api-key $(NugetAPIKey) 

- script: echo $(Build.BinariesDirectory)
- script: echo $(Build.BinariesDirectory)/autoupgrade.$(Major).$(Minor).$(Patch).nupkg
- script: echo $(NugetAPIKey)
- script: echo dotnet nuget push $(Build.BinariesDirectory)/autoupgrade.$(Major).$(Minor).$(Patch).nupkg --source https://nuget.org/api/v2/ --api-key $(NugetAPIKey) 
