version: '2'
services:
  dotnettest:
    image: ${DOTNET_SDK_IMAGE}
    volumes:
        - .:/build
        - nuget:/${PACKAGE_VOLUME_PATH}
    working_dir: /build
    entrypoint: ["dotnet", "test", "--configuration", "Release", "--no-build", "--framework", "netcoreapp2.1"]
  monotest:
    image: ${MONO_IMAGE}
    volumes:
        - .:/build
        - nuget:/${PACKAGE_VOLUME_PATH}
    working_dir: /build
    entrypoint: ["bash", "/build/ci-build/mono_test.sh"]
volumes:
  nuget:
    external:
      name: ${PACKAGE_VOLUME_NAME}